// Generates bundled JSON Schemas for the connector tools from the single source
// of truth: the OpenAPI 3.1 component schemas in the `@laddro-app/schemas` repo
// (the SAME schemas career-api validates against). Run locally; the output TS
// modules are committed so the build/runtime is self-contained.
//
//   node scripts/gen-schemas.mjs
//
// Re-run whenever resume.v1.yaml / cover-letter.v1.yaml change in laddro-schemas.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import yaml from "js-yaml";

const here = dirname(fileURLToPath(import.meta.url));
const SCHEMAS_REPO =
  process.env.LADDRO_SCHEMAS_DIR ||
  join(here, "..", "..", "laddro-schemas");

function buildSchema(yamlRelPath, rootName, id) {
  const doc = yaml.load(readFileSync(join(SCHEMAS_REPO, yamlRelPath), "utf8"));
  const schemas = doc?.components?.schemas;
  if (!schemas || !schemas[rootName]) {
    throw new Error(`No components.schemas.${rootName} in ${yamlRelPath}`);
  }
  // Rewrite OpenAPI refs to JSON-Schema $defs refs, then nest every component
  // schema under $defs with the named root reachable via the top-level $ref.
  const defs = JSON.parse(
    JSON.stringify(schemas).replaceAll("#/components/schemas/", "#/$defs/"),
  );
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: id,
    $ref: `#/$defs/${rootName}`,
    $defs: defs,
  };
}

const resume = buildSchema(
  "resume/resume.v1.yaml",
  "Resume",
  "https://schemas.laddro.com/resume.v1.json",
);
const coverLetter = buildSchema(
  "cover-letter/cover-letter.v1.yaml",
  "CoverLetter",
  "https://schemas.laddro.com/cover-letter.v1.json",
);

const outDir = join(here, "..", "src", "generated");
mkdirSync(outDir, { recursive: true });

const banner =
  "// AUTO-GENERATED by scripts/gen-schemas.mjs from @laddro-app/schemas. Do not edit by hand.\n";
writeFileSync(
  join(outDir, "resumeSchema.ts"),
  banner +
    `export const resumeSchema = ${JSON.stringify(resume, null, 2)} as const;\n`,
);
writeFileSync(
  join(outDir, "coverLetterSchema.ts"),
  banner +
    `export const coverLetterSchema = ${JSON.stringify(coverLetter, null, 2)} as const;\n`,
);

console.log(
  `Generated resumeSchema (${Object.keys(resume.$defs).length} defs) + coverLetterSchema (${Object.keys(coverLetter.$defs).length} defs)`,
);
